### ISSUE TITLE
Finalize Installation fails with TAO git under 18.04 / PHP 7.2

### ISSUE THREAD

**Issue by danboid** [oat-sa/package-tao#37]
I have just tried again to get TAO git ( this repo eg https://github.com/oat-sa/package-tao.git ) to install under Ubuntu Server 18.04 with the default PHP 7.2.5. Everything checks out with composer fine, I run the install wizard and I get as far as the final screen but then when I click 'Install' a message briefly appears saying 'Deploying' but then nothing happens. If I try clicking on  'Install' again, the same happens - deploying, then nothing.

Apache prints something like the following to the error log each time I push the Install button:

```
[Wed Jul 04 13:01:29.752401 2018] [php7:error] [pid 959] [client 192.168.122.1:50782] PHP Fatal error:  Cannot use oat\\taoQtiItem\\model\\qti\\Object as Object because 'Object' is a special class name in /var/www/html/taoQtiItem/model/qti/ParserFactory.php on line 54, referer: http://192.168.122.128/tao/install/
```
I have attached the install.log file
[install.log.gz](https://github.com/oat-sa/package-tao/files/2163322/install.log.gz)

**Comment by danboid** [comment]
I have also tried running taoInstall.php from the server cli as documented in the README for this repo but that fails in pretty much the same way ie many

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/tao/helpers/translation/class.POUtils.php on line 84
```

Warnings followed by:

```
PHP Fatal error:  Cannot use oat\taoQtiItem\model\qti\Object as Object because 'Object' is a special class name in /var/www/html/taoQtiItem/model/qti/ParserFactory.php on line 54
```

**Comment by jeppebundsgaard** [comment]
After updating to 18.04 and PHP 7.2, I get the same errors in the logs. Did you find a solution?

**Comment by jeppebundsgaard** [comment]
Yes, I found out that TAO doesn't work with PHP7.2, so I had to downgrade to 7.0... I have tried to find where I read that, but all I can find right now, is this: https://userguide.taotesting.com/3.2/introduction/installing-tao.html - which just says that TAO works with PHP 5.5 or higher...

**Comment by PremiumWindel** [comment]
thanks

**Comment by PremiumWindel** [comment]
Ok. On my server it works with php7.2.

**Comment by stone212** [comment]
@PremiumWindel So you don't get stuck on Finalize Installation like everyon else with PHP 7.2?  Maybe the cause is different then.

**Comment by sodok** [comment]
I had the same errors when using PHP7.2 instead of PHP7.4 
I tried to run the installation on the command line, and now this is displayed:

#0 /var/www/html/tao/generis/common/persistence/sql/pdo/class.Driver.php(130): PDO->__construct('mysql:dbname='', '', '', Array)
#1 /var/www/html/tao/generis/common/persistence/class.Manager.php(165): common_persistence_sql_pdo_Driver->connect('default', Array)
#2 /var/www/html/tao/generis/common/persistence/class.Manager.php(140): common_persistence_Manager->createPersistence('default')
#3 /var/www/html/tao/generis/core/kernel/persistence/smoothsql/class.SmoothModel.php(83): common_persistence_Manager->getPersistenceById('default')
#4 /var/www/html/tao/generis/core/kernel/persistence/smoothsql/class.Resource.php(57): core_kernel_persistence_smoothsql_SmoothModel->getPersistence()
#5 /var/www/html/tao/generis/core/kernel/persistence/smoothsql/class.Class.php(67): core_kernel_persistence_smoothsql_Resource->getPersistence()
#6 /var/www/html/tao/generis/core/kernel/persistence/smoothsql/class.Class.php(51): core_kernel_persistence_smoothsql_Class->getRecursiveSubClasses(Object(core_kernel_classes_Class))
#7 /var/www/html/tao/generis/core/kernel/persistence/smoothsql/class.Class.php(495): core_kernel_persistence_smoothsql_Class->getSubClasses(Object(core_kernel_classes_Class), true)
#8 /var/www/html/tao/generis/core/kernel/persistence/smoothsql/class.Class.php(347): core_kernel_persistence_smoothsql_Class->getFilteredQuery(Object(core_kernel_classes_Class), Array, Array)
#9 /var/www/html/tao/generis/core/kernel/classes/class.Class.php(267): core_kernel_persistence_smoothsql_Class->searchInstances(Object(core_kernel_classes_Class), Array, Array)
#10 /var/www/html/tao/funcAcl/helpers/CacheHelper.php(111): core_kernel_classes_Class->searchInstances(Array, Array)
#11 /var/www/html/tao/funcAcl/models/FuncAcl.php(47): oat\funcAcl\helpers\CacheHelper::getControllerAccess('tao_actions_Mai...')
#12 /var/www/html/tao/tao/models/classes/accessControl/func/AclProxy.php(82): oat\funcAcl\models\FuncAcl->accessPossible(Object(oat\oatbox\user\AnonymousUser), 'tao_actions_Mai...', 'index')
#13 /var/www/html/tao/tao/models/classes/accessControl/func/AclProxy.php(74): oat\tao\model\accessControl\func\AclProxy::accessPossible(Object(oat\oatbox\user\AnonymousUser), 'tao_actions_Mai...', 'index')
#14 /var/www/html/tao/tao/models/classes/accessControl/AclProxy.php(81): oat\tao\model\accessControl\func\AclProxy->hasAccess(Object(oat\oatbox\user\AnonymousUser), 'tao_actions_Mai...', 'index', Array)
#15 /var/www/html/tao/tao/models/classes/routing/ActionEnforcer.php(99): oat\tao\model\accessControl\AclProxy::hasAccess(Object(oat\oatbox\user\AnonymousUser), 'tao_actions_Mai...', 'index', Array)
#16 /var/www/html/tao/tao/models/classes/routing/ActionEnforcer.php(123): oat\tao\model\routing\ActionEnforcer->verifyAuthorization()
#17 /var/www/html/tao/tao/models/classes/routing/TaoFrontController.php(86): oat\tao\model\routing\ActionEnforcer->execute()
#18 /var/www/html/tao/tao/models/classes/mvc/Bootstrap.php(332): oat\tao\model\routing\TaoFrontController->legacy(Object(common_http_Request))
#19 /var/www/html/tao/tao/models/classes/mvc/Bootstrap.php(172): oat\tao\model\mvc\Bootstrap->mvc()
#20 /var/www/html/tao/tao/models/classes/mvc/Bootstrap.php(234): oat\tao\model\mvc\Bootstrap->dispatchHttp()
#21 /var/www/html/tao/index.php(31): oat\tao\model\mvc\Bootstrap->dispatch()
#22 {main}

**Comment by dnapier** [comment]
Having this exact issue, almost exactly two years later. Tried setting module mode to development, no dice.
