### ISSUE TITLE
issue when creating a new object 500:

### ISSUE THREAD

**Issue by iouss** [oat-sa/package-tao#50]
Hello,

I have got some issue when creating a new object like a class or test 
"The class URI must be provided in the id parameter" or 500:

The apache log show this error 👍 
Do you have any solution for that plz ?
Thanks 

`[Tue Apr 30 08:14:43.390392 2019] [:error] [pid 9650] [client 195.25.115.25:15906] PHP Fatal error:  Uncaught Error: Call to a member function getUri() on null in /var/www/html/tao/tao/actions/form/class.Clazz.php:222\nStack trace:\n#0 /var/www/html/tao/tao/helpers/form/class.FormContainer.php(100): tao_actions_form_Clazz->initElements()\n#1 /var/www/html/tao/tao/actions/form/class.Clazz.php(62): tao_helpers_form_FormContainer->__construct(Array)\n#2 /var/www/html/tao/tao/actions/class.PropertiesAuthoring.php(299): tao_actions_form_Clazz->__construct(Object(core_kernel_classes_Class), Array, Array, 'simple')\n#3 /var/www/html/tao/tao/actions/class.RdfController.php(160): tao_actions_PropertiesAuthoring->getClassForm(Object(core_kernel_classes_Class))\n#4 /var/www/html/tao/taoItems/actions/class.Items.php(229): tao_actions_RdfController->getClassForm(Object(core_kernel_classes_Class), Object(core_kernel_classes_Class))\n#5 [internal function]: taoItems_actions_Items->editItemClass()\n#6 /var/www/html/tao/tao/models/classes/routing/ActionEnforcer.php(145): call_user_func_array(Array, Array)\n#7 /var/www/html/tao/tao/mo in /var/www/html/tao/tao/actions/form/class.Clazz.php on line 222, referer: http://ec2-35-180-94-144.eu-west-3.compute.amazonaws.com/tao/tao/Main/index?structure=items&ext=taoItems&section=manage_items`

**Comment by quangdatnth** [comment]
Same error here

**Comment by bserrao** [comment]
I managed to solve this error like was reported here [https://forum.taotesting.com/discussion/527/the-class-uri-must-be-provided-in-the-id-parameter](https://forum.taotesting.com/discussion/527/the-class-uri-must-be-provided-in-the-id-parameter)

I looked at acess_log and search for the name of the rdf called. In my case it was first.rdf (i don't know why... by the way if you know how to change this let me know)
Then updated  config/generis.conf.php, /config/generis/uriProvider.conf.php and database models.
