### ISSUE TITLE
Login failure after switching to PHP 7.4

### ISSUE THREAD

**Issue by AmritasyaPutra** [oat-sa/package-tao#66]
I was using with PHP 7.3 and when I moved to PHP 7.4 I am not able to login. I cannot selectively go back to PHP 7.4 because other websites on the shared hosting have all migrated to PHP 7.4, this is the only website having issues. Please find below the detailed error log, I hope this will be sufficient to troubleshoot.

[14-May-2020 10:01:44 Asia/Kolkata] PHP Fatal error:  Uncaught TypeError: core_kernel_classes_Resource::__serialize() must return an array in /home/705D5A6/quiz.705D5A6.in/tao/models/classes/mvc/Bootstrap.php:183
Stack trace:
#0 /home/705D5A6/quiz.705D5A6.in/tao/models/classes/mvc/Bootstrap.php(183): session_write_close()
#1 /home/705D5A6/quiz.705D5A6.in/tao/models/classes/mvc/Bootstrap.php(234): oat\tao\model\mvc\Bootstrap->dispatchHttp()
#2 /home/705D5A6/quiz.705D5A6.in/index.php(31): oat\tao\model\mvc\Bootstrap->dispatch()
#3 {main}
  thrown in /home/705D5A6/quiz.705D5A6.in/tao/models/classes/mvc/Bootstrap.php on line 183

**Comment by sodok** [comment]
I have the same problem. Also when I switch back to PHP7.2 it says "tao INFO could not find driver {"file":/var/www/html/tao/tao/models/classes/mvc/error/ResponsesAbstract.php", "line":134}" and a hashed uid. This doesn't help me much. Neither in PHP7.2 nor in PHP7.4 I can make it work, although in PHP7.4 at least the guest access works. But in PHP7.4 I have exactly the same error as as AmritasyaPutra with exactly the same stack trace, caught as a "critical PHP error". Please fix this.

**Comment by dnapier** [comment]
I'm having the same experience that @sodok described.

- Ubuntu 18.04
- PHP 7.2
- Apache 2.4

**Comment by dnapier** [comment]
So, as it turns out, I get this error when installing via the taoInstall.php script. When using the web installer, I still get an error, but it functions after a reboot. I'm now trying the install using a config file, although functionality which generates a template doesn't seem to exist that I've found. Maybe would be a good feature request?

**Comment by dnapier** [comment]
Using the web installer with the same information yields:
![write-error](https://user-images.githubusercontent.com/19673339/86376186-a03f5000-bc54-11ea-9a30-a44b62977811.png)
Although, this doesn't seem to be the end of the road, as the visiting http://<domain>/tao yields a working server.

**Comment by DMiurge** [comment]
Is there any news on that matter?  I'm still getting this error.

> [Sun Oct 11 01:14:29.178354 2020] [php7:error] [pid 22636:tid 1808] [client ::1:58163] PHP Fatal error:  Uncaught TypeError: core_kernel_classes_Resource::__serialize() must return an array in C:\\xampp\\htdocs\\tao\\tao\\models\\classes\\mvc\\Bootstrap.php:183\nStack trace:\n#0 C:\\xampp\\htdocs\\tao\\tao\\models\\classes\\mvc\\Bootstrap.php(183): session_write_close()\n#1 C:\\xampp\\htdocs\\tao\\tao\\models\\classes\\mvc\\Bootstrap.php(234): oat\\tao\\model\\mvc\\Bootstrap->dispatchHttp()\n#2 C:\\xampp\\htdocs\\tao\\index.php(31): oat\\tao\\model\\mvc\\Bootstrap->dispatch()\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\tao\\tao\\models\\classes\\mvc\\Bootstrap.php on line 183, referer: http://localhost/tao/tao/Main/login?redirect=%2Ftao%2FtaoCe%2FMain%2Findex&msg=Access%20denied.%20Please%20renew%20your%20authentication%21
[Sun Oct 11 01:14:29.192366 2020] [php7:notice] [pid 22636:tid 1808] [client ::1:58163] PHP Notice:  session_start(): Unexpected end of serialized data in C:\\xampp\\htdocs\\tao\\tao\\models\\classes\\mvc\\Bootstrap.php on line 279, referer: http://localhost/tao/tao/Main/login?redirect=%2Ftao%2FtaoCe%2FMain%2Findex&msg=Access%20denied.%20Please%20renew%20your%20authentication%21
[Sun Oct 11 01:14:29.192366 2020] [php7:warn] [pid 22636:tid 1808] [client ::1:58163] PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in C:\\xampp\\htdocs\\tao\\tao\\models\\classes\\mvc\\Bootstrap.php on line 279, referer: http://localhost/tao/tao/Main/login?redirect=%2Ftao%2FtaoCe%2FMain%2Findex&msg=Access%20denied.%20Please%20renew%20your%20authentication%21

I don't want to use the installer since I've already a working xampp. Is there a way to fix this without reinstallation?

**Comment by iamshouvikmitra** [comment]
Any luck?

**Comment by nikolaygekht** [comment]
Any news? I have exactly the same problem after installation of 3.3-rc02 at ubuntu 20.04 and PHP 7.4
